version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback 
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - setup_remote_docker
      - run: docker login -u $USER_DOCKER  -p $PASSWORD_DOCKER
      - run:
          name: "Build Docker"
          command:  |
              cp Dockerfile.production  Dockerfile
              docker build -t onikingkong/traindevops01:latest .
              docker build -t onikingkong/traindevops01:${VER} .
              docker push onikingkong/traindevops01:latest
              docker push onikingkong/traindevops01:${VER}
  test:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps: 
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback 
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  ship:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps: 
      - run: echo Done 
  deploy:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: "Call to rancuer to deploy"
          command: |
            docker run --rm -it \
              -e CATTLE_ACCESS_KEY="$CATTLE_ACCESS_KEY" \
              -e CATTLE_SECRET_KEY="$CATTLE_SECRET_KEY" \
              -e CATTLE_URL="$CATTLE_URL" \
              etlweather/gaucho upgrade $RANCUER_EXAMPLE_NODEJS \
              --imageUuid 'docker:onikingkong/traindevops01:latest' \
              --batch_size 3 --start_first \
              --auto_complete --timeout 600
      - run: echo Done
workflows:
  version: 2
  build_test_ship_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - ship:
          requires:
            - build
            - test 
      - deploy:
          requires:
            - build
            - test
            - ship
