version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback 
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - setup_remote_docker
      - run: docker login -u $USER_DOCKER  -p $PASSWORD_DOCKER
      - run:
          name: "Build Docker"
          command:  |
              cp Dockerfile.production  Dockerfile
              docker build -t onikingkong/traindevops01:latest .
              docker build -t onikingkong/traindevops01:${VER} .
              docker push onikingkong/traindevops01:latest
              docker push onikingkong/traindevops01:${VER}
      - run:
          name: "Deploy Docker"
          command:  |
              docker run --rm -it \
              -e CATTLE_ACCESS_KEY="$CATTLE_ACCESS_KEY" \
              -e CATTLE_SECRET_KEY="$CATTLE_SECRET_KEY" \
              -e CATTLE_URL="$CATTLE_URL" \
              etlweather/gaucho upgrade $SEVICE_ID \
              --imageUuid 'onikingkong/traindevops01:latest' \
              --batch_size 1 --start_first \
              --auto_complete --time 600 \
              /
      - run: echo Done

